### ISSUE TITLE
Failed to run `make -j4`

### ISSUE THREAD

**Issue by Ads20000** [mjg59/xevilteddy#3]
Using `SNAPCRAFT_CONTAINER_BUILDS=1 snapcraft` (which lets me build in a persistent Ubuntu 16.04 LXD container instead of either a non-persistent one with `snapcraft cleanbuild` or just using `snapcraft`), I get the following error:

```
make -j4
gcc -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"xteddy\" -DVERSION=\"1.1\" -DHAVE_LIBXPM=1 -DPIXMAP_PATH=\"/include/X11/pixmaps\" -I.     -g -O2 -MT xteddy.o -MD -MP -MF .deps/xteddy.Tpo -c -o xteddy.o xteddy.c
xteddy.c:25:10: fatal error: X11/extensions/XTest.h: No such file or directory
 #include <X11/extensions/XTest.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:423: recipe for target 'xteddy.o' failed
make: *** [xteddy.o] Error 1
Failed to run 'make -j4' for 'xteddy': Exited with code 2.
Verify that the part is using the correct parameters and try again.
```

Is this because of the setup I'm using or is this a bug in what I'm trying to build?

<details>
<summary>Version</summary>

```
$ snap info snapcraft
tracking:  candidate
installed:   2.40.1              (1345) 49MB classic
$ snap version
snap    2.32.1
snapd   2.32.1
series  16
ubuntu  17.10
kernel  4.13.0-37-generic
$ snap info core
tracking:  beta
installed:   16-2.32.1 (4327) 86MB core
$ snap info lxd
tracking:  stable
installed:       2.21        (5866) 49MB -
```

</details>

**Comment by kugg** [comment]
Hi, this is a missing build dependency.
In snapcraft.yaml change build-packages to "build-packages: [libxpm-dev, libxtst-dev, libxext-dev]" to make snapcraft fetch the missing headers.
If you are compiling directly with make, please install libxtst-dev and libxext-dev prior to running make.

There is a fix at https://github.com/mjg59/xevilteddy/pull/4.
